### ISSUE TITLE
 [@vue/compiler-sfc] <script> and <script setup> must have the same language type.

### ISSUE THREAD

**Issue by NewCoder798** [yifengyoujian/unplugin-vue-setup-extend#110]
"unplugin-vue-setup-extend": "^0.3.2",
"vite": "^4.0.4",
 "vue": "3.2.44"
// vite.config.js
import VueSetupExtend from 'unplugin-vue-setup-extend/vite'
plugins: [VueSetupExtend()],

Error: [@vue/compiler-sfc] <script> and <script setup> must have the same language type.

**Comment by yifengyoujian** [comment]
有具体的代码吗

**Comment by NewCoder798** [comment]
> 有具体的代码吗

回退到"unplugin-vue-setup-extend": "^0.3.0",没问题，0.3.1没试过，应该是解析<script>上的属性时有点问题
代码：https://gitee.com/NewCoderMCL/vuepress-ui/tree/feature-pnpm/
我现在使用的版本是0.3.0，你可以直接修改到0.3.2试下

**Comment by yifengyoujian** [comment]
#116 解决了
