### ISSUE TITLE
[nuxt] Cannot restart nuxt:  Cannot read properties of undefined (reading 'extendBuild')

### ISSUE THREAD

**Issue by szulcus** [yifengyoujian/unplugin-vue-setup-extend#80]
Like below. Is module `unplugin-vue-setup-extend/nuxt` available for the latest stable version of Nuxt (3.0.0)?
Field `buildModules` is now unavailable: https://nuxt.com/docs/migration/configuration#modules

**Comment by yifengyoujian** [comment]
To find a way to do this, go to examples

**Comment by szulcus** [comment]
@yifengyoujian Either the documentation has been updated or I missed it. Anyway, after switching to the vite plugin everything works, thanks for the reply!
